"""Routes weights in TTR: "Europe". """

routes = [
    {
        "city_a": "Edinburgh",
        "city_b": "London",
        "weight": 4,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "London",
        "city_b": "Dieppe",
        "weight": 2,
        "locomotives": 1,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "London",
        "city_b": "Amsterdam",
        "weight": 2,
        "locomotives": 2,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Brest",
        "city_b": "Paris",
        "weight": 3,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Brest",
        "city_b": "Dieppe",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Dieppe",
        "city_b": "Paris",
        "weight": 1,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Paris",
        "city_b": "Bruxelles",
        "weight": 2,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Bruxelles",
        "city_b": "Amsterdam",
        "weight": 1,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Dieppe",
        "city_b": "Bruxelles",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Paris",
        "city_b": "Pamplona",
        "weight": 4,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Pamplona",
        "city_b": "Brest",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Madrid",
        "city_b": "Lisboa",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Lisboa",
        "city_b": "Cadiz",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Cadiz",
        "city_b": "Madrid",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Madrid",
        "city_b": "Pamplona",
        "weight": 3,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": True,
    },
    {
        "city_a": "Barcelona",
        "city_b": "Madrid",
        "weight": 2,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Barcelona",
        "city_b": "Pamplona",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Barcelona",
        "city_b": "Marseille",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Paris",
        "city_b": "Frankfurt",
        "weight": 3,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Paris",
        "city_b": "Zürich",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Zürich",
        "city_b": "Marseille",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Zürich",
        "city_b": "München",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Frankfurt",
        "city_b": "Essen",
        "weight": 2,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Essen",
        "city_b": "Amsterdam",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Amsterdam",
        "city_b": "Frankfurt",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Bruxelles",
        "city_b": "Frankfurt",
        "weight": 2,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Frankfurt",
        "city_b": "München",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Essen",
        "city_b": "Berlin",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Essen",
        "city_b": "København",
        "weight": 3,
        "locomotives": 1,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "København",
        "city_b": "Stockholm",
        "weight": 3,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Stockholm",
        "city_b": "Petrograd",
        "weight": 8,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Berlin",
        "city_b": "Danzig",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Danzig",
        "city_b": "Riga",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Riga",
        "city_b": "Petrograd",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Danzig",
        "city_b": "Warszawa",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Warszawa",
        "city_b": "Wien",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wien",
        "city_b": "Berlin",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wien",
        "city_b": "Budapest",
        "weight": 1,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Venezia",
        "city_b": "Zürich",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "München",
        "city_b": "Wien",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Venezia",
        "city_b": "Roma",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Roma",
        "city_b": "Brindisi",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Brindisi",
        "city_b": "Palermo",
        "weight": 3,
        "locomotives": 1,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Marseille",
        "city_b": "Roma",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Marseille",
        "city_b": "Paris",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Budapest",
        "city_b": "Zagreb",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Zagreb",
        "city_b": "Wien",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Budapest",
        "city_b": "Sarajevo",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sarajevo",
        "city_b": "Zagreb",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sarajevo",
        "city_b": "Sofia",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Sofia",
        "city_b": "Bucuresti",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Bucuresti",
        "city_b": "Budapest",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Bucuresti",
        "city_b": "Constantinople",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sofia",
        "city_b": "Athina",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Constantinople",
        "city_b": "Angora",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Angora",
        "city_b": "Smyrna",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Smyrna",
        "city_b": "Athina",
        "weight": 2,
        "locomotives": 1,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Athina",
        "city_b": "Brindisi",
        "weight": 4,
        "locomotives": 1,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Constantinople",
        "city_b": "Sevastopol",
        "weight": 4,
        "locomotives": 2,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Budapest",
        "city_b": "Kiev",
        "weight": 6,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Moskva",
        "city_b": "Petrograd",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wilno",
        "city_b": "Warszawa",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wilno",
        "city_b": "Riga",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wilno",
        "city_b": "Smolensk",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Smolensk",
        "city_b": "Moskva",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Kharkov",
        "city_b": "Kiev",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Kharkov",
        "city_b": "Rostov",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Rostov",
        "city_b": "Sochi",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sevastopol",
        "city_b": "Sochi",
        "weight": 2,
        "locomotives": 1,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Madrid",
        "city_b": "Barcelona",
        "weight": 2,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Pamplona",
        "city_b": "Marseille",
        "weight": 4,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Frankfurt",
        "city_b": "Berlin",
        "weight": 3,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Warszawa",
        "city_b": "Berlin",
        "weight": 4,
        "locomotives": 0,
        "is_double": True,
        "is_gallery": False,
    },
    {
        "city_a": "Warszawa",
        "city_b": "Kiev",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Kiev",
        "city_b": "Wilno",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Wilno",
        "city_b": "Petrograd",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Kiev",
        "city_b": "Smolensk",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Kiev",
        "city_b": "Bucuresti",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Bucuresti",
        "city_b": "Sevastopol",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sevastopol",
        "city_b": "Rostov",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Sevastopol",
        "city_b": "Erzurum",
        "weight": 4,
        "locomotives": 2,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Erzurum",
        "city_b": "Angora",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Erzurum",
        "city_b": "Sochi",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Kharkov",
        "city_b": "Moskva",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Constantinople",
        "city_b": "Sofia",
        "weight": 3,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Constantinople",
        "city_b": "Smyrna",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
    {
        "city_a": "Smyrna",
        "city_b": "Palermo",
        "weight": 6,
        "locomotives": 2,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Athina",
        "city_b": "Sarajevo",
        "weight": 4,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Palermo",
        "city_b": "Roma",
        "weight": 4,
        "locomotives": 1,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Venezia",
        "city_b": "Zagreb",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": False,
    },
    {
        "city_a": "Venezia",
        "city_b": "München",
        "weight": 2,
        "locomotives": 0,
        "is_double": False,
        "is_gallery": True,
    },
]
